### ISSUE TITLE
use phpunit.xml

### ISSUE THREAD

**Issue by unional** [Heris-IT/vscode-phpunit-watcher#1]
Hi, thanks for creating this extension!

Currently, it doesn't work for me because I don't put my tests under the `tests` folder.
Is it possible for the extension to load the `phpunit.xml` in the project?

I do have it setup correctly so running phpunit from cli will work.

Thanks!

**Comment by RikScheffer** [comment]
Hi, good suggestion. I will look into it.

For the short term: you can specify the arguments/test folder in the extension settings and chance the default 'tests' to your preference.

**Comment by unional** [comment]
I tried changing `phpunit-watcher.phpunitArguments` but it doesn't work, still 0 test executed.

btw, here is the project I'm working on: https://github.com/justland/just-func-php

Tried setting `phpunit-watcher.phpunitArguments: "php"`.

**Comment by RikScheffer** [comment]
you can specify the config file with `phpunit-watcher.phpunitArguments`, see for example this screenshots:
![image](https://user-images.githubusercontent.com/6080708/109284376-144fe900-7820-11eb-8349-2fc9a5d71f24.png)
or with this ./vscode/settings.json:
`{
    "phpunit-watcher.phpunitArguments": "-c config.xml"
}`

**Comment by unional** [comment]
Thank~
